name: Manual
on:
  workflow_dispatch:
    inputs:
      log-label:
        type: choice
        options:
          - info
          - warn
          - error
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"